version: '2'
services:
  app:
    build:
      context: .
    image: xdebug-example:latest
    volumes:
     - ./:/var/www/html
    ports:
     - "80:80"
  docker-mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./docker-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=blog